# yaml-language-server: $schema=https://app.opslevel.com/public/opslevel.schema.yml
---
version: 1
service:

  # The name of your repository.
  name: dbt-checkpoint-pleo

  # The state of the code within the repository.
  lifecycle: generally_available

  # The lower-case top-level name of your github team name, 
  # not <team>-backend/frontend. 
  # If the team name contains spaces, replace these with hyphens/dashes.
  # This field should be set to the team who stewards the repository.
  owner: analytics-empowerment

  # The programming language of your repository.
  # Usually Kotlin or TypeScript.
  language: sql

  # How you describe your repository.
  # Usually the description of your repository.
  description: |-
    This repository is a copy of [dbt-checkpoint](https://github.com/dbt-checkpoint/dbt-checkpoint).
    The only difference is that this repository contains modifications to checkpoints which don't work directly "out-of-the-box",
    and thus needs to be modified to work with our dbt project.

  # Any aliases you give your repository.
  aliases: 
    - <any project aliases in package.json, build.gradle or the root folder>

  # Repository information to allow OpsLevel to link to your repository.
  repositories:
		- name: pleo-io/dbt-checkpoint-pleo
      provider: github
      display_name: dbt-checkpoint-pleo @ terraform

  # Any tags you would like to add to the service definition in OpsLevel.
  tags:
      # Which type of service the repository defines. 
      #
      # Use:
      #  - `service` for web services (moons)
      #  - `application` for downloadable software (such as an iOS/Android app,
      #     CLI tool, standalone executable). This also includes e.g. web apps.
      #  - `library` for software used by other components
      - `configuration` for repos that contain pure configuration (such as
      #    setup of danger or renovate).
      #  - `hiring-challenge` for our hiring challenge
      #  - `serverless-function` for lambdas such as space-rocks
			#  - `documentation` for documentation repositories e.g. .github

    - key: type
      value: configuration